### ISSUE TITLE
Possibility to deploy multiple lambdas/handlers

### ISSUE THREAD

**Issue by evdh** [marcinczeczko/quarkus-lambda-native#1]
Is it possible to have multiple handlers/lambda in your code and individually deploy them? So, we would have 'HelloLambda1' and 'HelloLambda2' and then refer to them in the serverless.yml? If not, the alternatives are to either build each lambda individually (very slow if you have 100 lambdas) or else to have a single lambda handle multiple endpoints (ie, have 10 lambdas each handling 10 endpoints by looking at the path/url coming in). Both are not ideal. Any ideas/suggestions?

**Comment by marcinczeczko** [comment]
Yep, serveless framework allows to do so, see here: https://serverless.com/framework/docs/providers/aws/guide/packaging#individual-function-packages

You can configure it in `serveless.yml` as follows
```yaml
package:
  individually: true

functions:
  HelloLambda1:
    handler: Handler
    package:
       artifact: <path to your handler zip>
    ...
  HelloLambda2:
    handler: Handler
    package:
       artifact: <path to your handler zip>
    ....
  HelloLambda3:
    handler: Handler
    package:
       artifact: <path to your handler zip>
   ...
```
